"""
Custom Citizens API Router

REST API endpoints for managing reusable custom citizen templates.
"""

import logging
from typing import Optional, List

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.models.database import get_db
from app.models.models import CustomCitizenTemplate
from app.models.schemas import (
    CustomCitizenCreateRequest,
    CustomCitizenUpdateRequest,
    CustomCitizenTemplateResponse,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/custom-citizens", tags=["custom-citizens"])


TRAITS_PERSONA_TEMPLATE = """Create a persona for a citizens' assembly participant with the following characteristics:

- Name: {name}
- Background: {background}
- Core Values: {values}
- Political Leaning: {political_leaning}
- Demographic Tags: {tags}

Write a detailed system prompt that will guide this persona during policy deliberation. The persona should:
1. Have a clear, authentic voice rooted in their background and values
2. Be capable of respectful engagement with different viewpoints
3. Draw on personal experiences consistent with their background
4. Stay true to their core values while remaining open to evidence

Return ONLY the system prompt text (no JSON, no formatting). The system prompt should be written in second person ("You are...").
"""


async def _generate_system_prompt_from_traits(
    name: str,
    background_summary: Optional[str],
    key_values: Optional[List[str]],
    political_leaning: Optional[str],
    demographic_tags: Optional[List[str]],
) -> str:
    """Use the Writer LLM to generate a system_prompt from high-level traits."""
    from app.llm_client import get_llm_client
    from app.prompt_loader import get_writer_prompt

    llm = get_llm_client(purpose="writer")

    prompt = TRAITS_PERSONA_TEMPLATE.format(
        name=name,
        background=background_summary or "Not specified",
        values=", ".join(key_values) if key_values else "Not specified",
        political_leaning=political_leaning or "Not specified",
        tags=", ".join(demographic_tags) if demographic_tags else "Not specified",
    )

    response = await llm.complete(
        prompt=prompt,
        system_prompt=get_writer_prompt(),
        temperature=0.7,
        max_tokens=1500,
    )

    if not response or not response.strip():
        # Fallback: generate a basic system prompt
        return _fallback_system_prompt(name, background_summary, key_values, political_leaning)

    # The response should be raw text (the system prompt itself)
    # Strip any markdown code fences if the LLM wrapped it
    text = response.strip()
    if text.startswith("```"):
        lines = text.split("\n")
        text = "\n".join(lines[1:])
        if text.endswith("```"):
            text = text[:-3].strip()

    return text


def _fallback_system_prompt(
    name: str,
    background_summary: Optional[str],
    key_values: Optional[List[str]],
    political_leaning: Optional[str],
) -> str:
    """Generate a basic system prompt without LLM."""
    values_str = ", ".join(key_values) if key_values else "fairness, community, common sense"
    leaning_str = political_leaning or "moderate"
    bg = background_summary or f"a citizen with {leaning_str} political views"

    return f"""You are {name}, {bg}. Your political outlook is generally {leaning_str}.

Your core values are {values_str}. During this assembly, you will share your perspective on policy issues based on your values and life experiences. Listen carefully to others, engage respectfully with different viewpoints, and remain open to evidence while staying true to your core beliefs.

Keep your responses concise and natural. You are a thoughtful citizen, not a political expert."""


@router.post("", response_model=CustomCitizenTemplateResponse, status_code=201)
async def create_custom_citizen(
    request: CustomCitizenCreateRequest,
    db: Session = Depends(get_db),
):
    """
    Create a custom citizen template.

    In 'traits' mode, the system_prompt is generated by the LLM from the
    provided traits. In 'full' mode, the system_prompt must be provided directly.
    """
    if request.mode not in ("traits", "full"):
        raise HTTPException(status_code=400, detail="mode must be 'traits' or 'full'")

    system_prompt = request.system_prompt

    if request.mode == "full":
        if not system_prompt:
            raise HTTPException(
                status_code=400,
                detail="system_prompt is required for 'full' mode"
            )
    elif request.mode == "traits":
        # Generate system_prompt from traits via LLM
        try:
            system_prompt = await _generate_system_prompt_from_traits(
                name=request.name,
                background_summary=request.background_summary,
                key_values=request.key_values,
                political_leaning=request.political_leaning,
                demographic_tags=request.demographic_tags,
            )
        except Exception as e:
            logger.error(f"Error generating system prompt from traits: {e}")
            system_prompt = _fallback_system_prompt(
                request.name, request.background_summary,
                request.key_values, request.political_leaning
            )

    template = CustomCitizenTemplate(
        name=request.name,
        mode=request.mode,
        background_summary=request.background_summary,
        key_values=request.key_values,
        demographic_tags=request.demographic_tags,
        political_leaning=request.political_leaning,
        system_prompt=system_prompt,
    )
    db.add(template)
    db.commit()
    db.refresh(template)

    logger.info(f"Created custom citizen template: {template.name} (id={template.id}, mode={template.mode})")
    return template


@router.get("", response_model=list[CustomCitizenTemplateResponse])
def list_custom_citizens(db: Session = Depends(get_db)):
    """List all custom citizen templates."""
    return db.query(CustomCitizenTemplate).order_by(
        CustomCitizenTemplate.created_at.desc()
    ).all()


@router.get("/{template_id}", response_model=CustomCitizenTemplateResponse)
def get_custom_citizen(template_id: int, db: Session = Depends(get_db)):
    """Get a single custom citizen template."""
    template = db.query(CustomCitizenTemplate).filter(
        CustomCitizenTemplate.id == template_id
    ).first()

    if not template:
        raise HTTPException(status_code=404, detail="Custom citizen template not found")

    return template


@router.put("/{template_id}", response_model=CustomCitizenTemplateResponse)
async def update_custom_citizen(
    template_id: int,
    request: CustomCitizenUpdateRequest,
    db: Session = Depends(get_db),
):
    """Update a custom citizen template."""
    template = db.query(CustomCitizenTemplate).filter(
        CustomCitizenTemplate.id == template_id
    ).first()

    if not template:
        raise HTTPException(status_code=404, detail="Custom citizen template not found")

    update_data = request.model_dump(exclude_unset=True)

    # If traits changed and mode is "traits", regenerate system_prompt
    traits_fields = {"background_summary", "key_values", "demographic_tags", "political_leaning", "name"}
    traits_changed = any(f in update_data for f in traits_fields)
    mode = update_data.get("mode", template.mode)

    if mode == "traits" and traits_changed and "system_prompt" not in update_data:
        # Apply updates to get current values
        name = update_data.get("name", template.name)
        bg = update_data.get("background_summary", template.background_summary)
        kv = update_data.get("key_values", template.key_values)
        pl = update_data.get("political_leaning", template.political_leaning)
        dt = update_data.get("demographic_tags", template.demographic_tags)

        try:
            update_data["system_prompt"] = await _generate_system_prompt_from_traits(
                name=name, background_summary=bg, key_values=kv,
                political_leaning=pl, demographic_tags=dt,
            )
        except Exception as e:
            logger.error(f"Error regenerating system prompt: {e}")
            update_data["system_prompt"] = _fallback_system_prompt(name, bg, kv, pl)

    for field, value in update_data.items():
        setattr(template, field, value)

    db.commit()
    db.refresh(template)

    logger.info(f"Updated custom citizen template {template_id}")
    return template


@router.delete("/{template_id}", status_code=204)
def delete_custom_citizen(template_id: int, db: Session = Depends(get_db)):
    """Delete a custom citizen template."""
    template = db.query(CustomCitizenTemplate).filter(
        CustomCitizenTemplate.id == template_id
    ).first()

    if not template:
        raise HTTPException(status_code=404, detail="Custom citizen template not found")

    db.delete(template)
    db.commit()

    logger.info(f"Deleted custom citizen template {template_id}")
